appTitle: BC Station Data - PCDS
pdpDataUrl: https://services.pacificclimate.org/data
sdsUrl: http://localhost:5000
baseMap: BC
stationsQpProvinces: BC
networkFilters: name != "PCIC Climate Variables"
#stationFilters: histories[0].province = "BC"
#stationDebugFetchOptions: false
#stationDebugFetchLimits: [100, 500, 1000, 2000, 4000, 8000]
#stationOffset: undefined
#stationLimit: undefined
#stationStride: undefined
#showReloadStationsButton: false
#timingEnabled: false
