#appTitle: BC Station Data - PCDS
#baseMap: BC
#
## Dev instance
#sdsUrl: https://services.pacificclimate.org/dev/met-data-portal-pcds/api/metadata/
## Local instance
##sdsUrl: http://localhost:5000
#stationsQpProvinces: BC
#
## Always necessary for CRMP database
#networkFilters: name != "PCIC Climate Variables"
#
## Dev instance
##pdpDataUrl: http://docker-dev01.pcic.uvic.ca:30507
#pdpDataUrl: https://services.pacificclimate.org/dev/met-data-portal-pcds/api/data/

appTitle: Western Arctic Weather Data
baseMap: YNWT

# Dev instance
#sdsUrl: https://services.pacificclimate.org/dev/met-data-portal-ynwt/meta
# Local instance
sdsUrl: http://localhost:5000
# We do not at present need to filter based on province (verify!)
#stationsQpProvinces: YK,NT
# We do not at present need to filter networks (verify!)
#networkFilters: ???

# Dev instance
pdpDataUrl: https://services.pacificclimate.org/dev/met-data-portal-ynwt/data

# Debug params
#stationFilters: histories[0].province = "BC"
#stationDebugFetchOptions: false
#stationDebugFetchLimits: [100, 500, 1000, 2000, 4000, 8000]
#stationOffset: undefined
#stationLimit: undefined
#stationStride: undefined
#showReloadStationsButton: false
#timingEnabled: false
