# This docker-compose uses the following shell environment variables:
#
# `SDP_TAG`: Image tag
# `SDP_PORT`: External port to map to
# `SDP_PUBLIC_URL`: Public URL of app
#
# Their values are set appropriately in the Makefile for use on a workstation.
# For use in a production setting, either set the shell
# variables appropriately when invoking docker-compose, or modify (a copy of)
# this file with the desired values.

version: '3.2'
services:
  frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: pcic/station-data-portal-frontend:${SDP_TAG}
    container_name: station-data-portal-frontend
    environment:
      - PUBLIC_URL=${SDP_PUBLIC_URL}
    env_file:
      - bc.env
    volumes:
      - type: bind
        source: ./bc-config.yaml
        target: /app/public/config.yaml
        read_only: true
    ports:
      - "${SDP_PORT}:8080"
