# This docker-compose uses the following shell environment variables:
#
# `SDP_TAG`: Image tag
# `SDP_PORT`: External port to map to
# `SDP_PUBLIC_URL`: Public URL of app
#
# Their values are set appropriately in the Makefile for use on a workstation.
# For use in a production setting, either set the shell
# variables appropriately when invoking docker-compose, or modify (a copy of)
# this file with the desired values.

version: '3.2'
services:
  frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: pcic/station-data-portal-frontend:${SDP_TAG}
    container_name: station-data-portal-frontend
    environment:
      - PUBLIC_URL=${SDP_PUBLIC_URL}
      - REACT_APP_BASE_MAP=YNWT
      - REACT_APP_BC_BASE_MAP_TILES_URL=http://142.104.230.53:30790/osm-bc-lite-test/{z}/{x}/{y}.png
      - REACT_APP_YNWT_BASE_MAP_TILES_URL=https://services.pacificclimate.org/tiles_north/{z}/{x}/{y}.png
      - REACT_APP_SDS_URL=http://docker-dev02.pcic.uvic.ca:30502
      - REACT_APP_PDP_DATA_URL=http://docker-dev02.pcic.uvic.ca:30500
    ports:
      - "${SDP_PORT}:8080"
